version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/sample-nodejs
hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      runas: ec2-user
  ApplicationStart:
    - location: deploy.sh
      runas: ec2-user

